name: ci.yml

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew clean build --no-daemon

      - name: List build/libs (debug)
        run: ls -la build/libs || echo "No libs"

      - name: Debug SBOM generation
        run: ./gradlew cyclonedxBom --info --rerun-tasks --no-daemon

      - name: Verify SBOM file
        run: test -f build/reports/bom.json && echo "SBOM file exists" || (echo "SBOM file is missing" && exit 1)

      - name: Sonar analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        run: ./gradlew sonar --no-daemon

      - name: Quality Gate
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        with:
          scanMetadataReportFile: build/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Trivy scan (filesystem)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            aquasec/trivy:latest fs /repo \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --format json \
            -o /repo/trivy-report.json

      - name: Rename SBOM with version
        run: |
          VERSION=${GITHUB_REF_NAME:-$(git rev-parse --short HEAD)}
          cp build/reports/bom.json "sbom-$VERSION.json"
          echo "SBOM_FILE=sbom-$VERSION.json" >> $GITHUB_ENV

      - name: Upload versioned SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: ${{ env.SBOM_FILE }}

      - name: Upload SBOM artifact
        if: always()   # se suba aunque falle alguna prueba (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: build/reports/bom.json

      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-dependency-report
          path: trivy-report.json